RESOURCE_ENDPOINT = 'NESE S3 Bucket Endpoint'
RESOURCE_QUOTA = 'NESE S3 Bucket Quota'
RESOURCE_OWNER = 'NESE Storage Owner'

ALLOCATION_BUCKETNAME = 'NESE S3 Bucket Name'
ALLOCATION_ACCESS_KEY = 'NESE S3 Bucket Access Key'
ALLOCATION_SECRET_KEY = 'NESE S3 Bucket Secret Key'

RESOURCE_TEXT_ATTRIBUTES = [
    RESOURCE_ENDPOINT,
    RESOURCE_OWNER
]

RESOURCE_INT_ATTRIBUTES = [
    RESOURCE_QUOTA
]

ALLOCATION_TEXT_ATTRIBUTES = [
    ALLOCATION_BUCKETNAME,
    ALLOCATION_ACCESS_KEY,
    ALLOCATION_SECRET_KEY
]
