version: "3.9"
services:
  minio:
    container_name: minio-osn
    environment:
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    image: quay.io/minio/minio
    command: server /data --address "0.0.0.0:9000" --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "${VIRTUAL_ENV}/compose/data:/data"