---
resources:
  - ../../coldfront-nerc/k8s/overlays/prod
  - ./vault
  - ./nese_secrets.yaml
  - ./minio_deployment.yaml
  - ./minio_service.yaml

patches:
  # Use staging for certs
  # - patch: |-
  #     - op: replace
  #       path: /metadata/annotations/cert-manager.io~1cluster-issuer
  #       value: letsencrypt-staging
  #   target:
  #     kind: Ingress

  # Change ingress hostname (part1)
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: coldfrontdev.mss.mghpcc.org
    target:
      kind: Ingress

  # Change ingress hostname (part2)
  - patch: |-
      - op: replace
        path: /spec/tls/0
        value: 
          hosts:
            - coldfrontdev.mss.mghpcc.org
          secretName: coldfrontdev-tls
    target:
      kind: Ingress

  - patch: |-
      - op: add
        path: /spec/data/-
        value:
          secretKey: EMAIL_HOST_USER
          remoteRef:
            key: accounts/aws/mghpcc/smtp
            property: EMAIL_HOST_USER
      - op: add
        path: /spec/data/-
        value:
          secretKey: EMAIL_HOST_PASSWORD
          remoteRef:
            key: accounts/aws/mghpcc/smtp
            property: EMAIL_HOST_PASSWORD
    target:
      kind: ExternalSecret
      name: coldfront-secrets

  # Debug environment stuff
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coldfront-configmap
      data:
        DEBUG: "True"
        PYTHONUNBUFFERED: "1"
        PYTHONPATH: "/code:/plugins"
        EMAIL_SUBJECT_PREFIX: '[ColdFront]'
        EMAIL_ADMIN_LIST: "culbertj@mghpcc.org, james.culbert@gmail.com"
        EMAIL_SENDER: "coldfrontadmin@mghpcc.org"
        EMAIL_TICKET_SYSTEM_ADDRESS: "culbertj@mghpcc.org"
        EMAIL_DIRECTOR_EMAIL_ADDRESS: "culbertj@mghpcc.org"
        EMAIL_PROJECT_REVIEW_CONTACT: "culbertj@mghpcc.org"
        EMAIL_DEVELOPMENT_EMAIL_LIST: "culbertj@mghpcc.org, james.culbert@gmail.com"
        CENTER_BASE_URL: "https://coldfrontdev.mss.mghpcc.org"
        # INITIAL_SETUP: "True"  
        OIDC_OP_AUTHORIZATION_ENDPOINT: "https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/auth"
        OIDC_OP_TOKEN_ENDPOINT: "https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/token"
        OIDC_OP_USER_ENDPOINT: "https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/userinfo"
        OIDC_OP_JWKS_ENDPOINT: "https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/certs"
        OIDC_AUTHENTICATION_CALLBACK_URL: "https://coldfrontdev.mss.mghpcc.org/oidc/callback/"
        KEYCLOAK_URL: 'https://keycloakdev.mss.mghpcc.org'

  # Switch to dev image
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coldfront-deployment
      spec:
        template:
          spec:
            hostAliases:
            - ip: "199.94.60.49"
              hostnames:
              - "keycloak.mss.mghpcc.org"
              - "keycloakdev.mss.mghpcc.org" 
            containers:
              - name: coldfront
                image: culbert/coldfront-nerc:latest
                imagePullPolicy: Never
                command: ["run_coldfront.sh"]
                args: ["coldfront"]
                envFrom:
                - configMapRef:
                    name: coldfront-configmap
                - secretRef:
                    name: coldfront-plugin-nese
                - secretRef:
                    name: coldfront-secrets

  # switch to dev image and new runscript w/qcluster arg
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coldfront-qcluster-deployment
      spec:
        template:
          spec:
            containers:
              - name: coldfront-qcluster
                image: culbert/coldfront-nerc:latest
                imagePullPolicy: Never
                command: ["run_coldfront.sh"]
                args: ["qcluster"]
                envFrom:
                - configMapRef:
                    name: coldfront-configmap
                - secretRef:
                    name: coldfront-plugin-nese
                - secretRef:
                   name: coldfront-secrets

  # Turn off scheduled  backups
  - patch: |-
      - op: replace
        path: /spec/backups/pgbackrest
        value: 
          image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
          global:
            repo1-retention-full: "1"
            repo1-retention-full-type: count
          manual:
            repoName: repo1
            options:
            - --type=full
          repos:
          - name: repo1
            volume:
              volumeClaimSpec:
                accessModes:
                - "ReadWriteOnce"
                resources:
                  requests:
                    storage: 5Gi
    target:
      name: .*-postgres-ha
