apiVersion: v1
kind: Service
metadata:
  name: nese-minio
spec:
  ports:
    - name: minioapi
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: minioconsole
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: coldfront
    plugin: nese
    deployment: minio
