apiVersion: v1
kind: ConfigMap
metadata:
  name: coldfront-plugin-nese
data:
  EMAIL_ENABLED: "True"
  EMAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_SUBJECT_PREFIX: '[ColdFront]'
  EMAIL_ADMIN_LIST: "culbertj@mghpcc.org, james.culbert@gmail.com"
  EMAIL_SENDER: "coldfrontadmin@mghpcc.org"
  EMAIL_TICKET_SYSTEM_ADDRESS: "culbertj@mghpcc.org"
  EMAIL_DIRECTOR_EMAIL_ADDRESS: "culbertj@mghpcc.org"
  EMAIL_PROJECT_REVIEW_CONTACT: "culbertj@mghpcc.org"
  EMAIL_DEVELOPMENT_EMAIL_LIST: "culbertj@mghpcc.org, james.culbert@gmail.com"
