apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coldfront-plugin-nese
  namespace: coldfront
spec:
  target:
    name: coldfront-plugin-nese
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - key: coldfront/coldfront-plugin-nese