---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: coldfront-plugin-nese
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: culbert/coldfront-nerc
      context: ../..
      docker:
        dockerfile: coldfront-plugin-nese/skaffold/Dockerfile
      sync:
        manual:
          - src: "coldfront-plugin-nese/src/**"
            dest: "/code"
            strip: "coldfront-plugin-nese/src/"

deploy:
  kustomize:
    paths:
      - .
  kubeContext: nerc-minikube
